// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type LogLevel string

const (
	LogLevelTrace    LogLevel = "trace"
	LogLevelInfo     LogLevel = "info"
	LogLevelWarning  LogLevel = "warning"
	LogLevelCritical LogLevel = "critical"
)

func (e *LogLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LogLevel(s)
	case string:
		*e = LogLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for LogLevel: %T", src)
	}
	return nil
}

type NullLogLevel struct {
	LogLevel LogLevel `json:"logLevel"`
	Valid    bool     `json:"valid"` // Valid is true if LogLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLogLevel) Scan(value interface{}) error {
	if value == nil {
		ns.LogLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LogLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLogLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LogLevel), nil
}

type File struct {
	ID                int64              `json:"id"`
	OwnerID           int64              `json:"ownerId"`
	EncryptedMetadata []byte             `json:"encryptedMetadata"`
	EncryptedKey      []byte             `json:"encryptedKey"`
	ParentID          int64              `json:"parentId"`
	Chunks            int32              `json:"chunks"`
	ChunkSize         int64              `json:"chunkSize"`
	Size              int64              `json:"size"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
}

type FileChunk struct {
	FileID     int64  `json:"fileId"`
	ChunkIndex int32  `json:"chunkIndex"`
	S3Key      string `json:"s3Key"`
}

type Folder struct {
	ID                int64              `json:"id"`
	EncryptedMetadata []byte             `json:"encryptedMetadata"`
	ParentID          pgtype.Int8        `json:"parentId"`
	OwnerID           int64              `json:"ownerId"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
}

type Log struct {
	ID                int64              `json:"id"`
	OwnerID           int64              `json:"ownerId"`
	Level             LogLevel           `json:"level"`
	Message           []byte             `json:"message"`
	EncryptedMetadata []byte             `json:"encryptedMetadata"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
}

type PublicShare struct {
	ID                int64              `json:"id"`
	Key               string             `json:"key"`
	FileID            int64              `json:"fileId"`
	OwnerID           int64              `json:"ownerId"`
	EncryptedKey      []byte             `json:"encryptedKey"`
	EncryptedMetadata []byte             `json:"encryptedMetadata"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt         pgtype.Timestamptz `json:"expiresAt"`
}

type Session struct {
	ID           int64              `json:"id"`
	RefreshToken string             `json:"refreshToken"`
	UserID       int64              `json:"userId"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt    pgtype.Timestamptz `json:"expiresAt"`
	LastUsedAt   pgtype.Timestamptz `json:"lastUsedAt"`
}

type Share struct {
	ID                int64              `json:"id"`
	FileID            int64              `json:"fileId"`
	SenderID          int64              `json:"senderId"`
	ReceiverID        int64              `json:"receiverId"`
	EncryptedFek      []byte             `json:"encryptedFek"`
	EncryptedMetadata []byte             `json:"encryptedMetadata"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt         pgtype.Timestamptz `json:"expiresAt"`
}

type SiteConfig struct {
	ID                       int16              `json:"id"`
	UploadExpirySeconds      int32              `json:"uploadExpirySeconds"`
	RegistrationOpen         bool               `json:"registrationOpen"`
	DefaultUserCapacityBytes int64              `json:"defaultUserCapacityBytes"`
	UpdatedAt                pgtype.Timestamptz `json:"updatedAt"`
}

type Upload struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"userId"`
	EncryptedMetadata []byte             `json:"encryptedMetadata"`
	ParentID          int64              `json:"parentId"`
	Chunks            int32              `json:"chunks"`
	ChunkSize         int64              `json:"chunkSize"`
	Size              int64              `json:"size"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	CompletedAt       pgtype.Timestamptz `json:"completedAt"`
	ExpiresAt         pgtype.Timestamptz `json:"expiresAt"`
}

type UploadChunk struct {
	UploadID   int64  `json:"uploadId"`
	ChunkIndex int32  `json:"chunkIndex"`
	S3Key      string `json:"s3Key"`
	Completed  bool   `json:"completed"`
}

type User struct {
	ID                   int64              `json:"id"`
	Email                string             `json:"email"`
	Username             string             `json:"username"`
	OpaqueRecord         []byte             `json:"opaqueRecord"`
	CredentialIdentifier []byte             `json:"credentialIdentifier"`
	Permission           int64              `json:"permission"`
	Capacity             int64              `json:"capacity"`
	KdfSalt              []byte             `json:"kdfSalt"`
	KdfMemoryCost        int32              `json:"kdfMemoryCost"`
	KdfTimeCost          int32              `json:"kdfTimeCost"`
	KdfParallelism       int32              `json:"kdfParallelism"`
	PublicKey            []byte             `json:"publicKey"`
	EncryptedPrivateKey  []byte             `json:"encryptedPrivateKey"`
	RootFolder           pgtype.Int8        `json:"rootFolder"`
	IsActive             bool               `json:"isActive"`
	IsLocked             bool               `json:"isLocked"`
	CreatedAt            pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt            pgtype.Timestamptz `json:"updatedAt"`
	LastLoginAt          pgtype.Timestamptz `json:"lastLoginAt"`
}
