// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeUploadChunk = `-- name: CompleteUploadChunk :exec
UPDATE upload_chunks
SET completed = TRUE
WHERE upload_id = $1 AND chunk_index = $2
`

type CompleteUploadChunkParams struct {
	UploadID   int64 `json:"uploadId"`
	ChunkIndex int32 `json:"chunkIndex"`
}

func (q *Queries) CompleteUploadChunk(ctx context.Context, arg CompleteUploadChunkParams) error {
	_, err := q.db.Exec(ctx, completeUploadChunk, arg.UploadID, arg.ChunkIndex)
	return err
}

const completeUploadSession = `-- name: CompleteUploadSession :exec
UPDATE uploads
SET completed_at = NOW()
WHERE id = $1 AND expires_at > NOW()
`

func (q *Queries) CompleteUploadSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeUploadSession, id)
	return err
}

const countActiveUploadSession = `-- name: CountActiveUploadSession :one
SELECT COUNT(*) FROM uploads
WHERE user_id = $1 AND completed_at IS NULL AND expires_at > NOW()
`

func (q *Queries) CountActiveUploadSession(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUploadSession, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLogsForOwner = `-- name: CountLogsForOwner :one
SELECT COUNT(*)::bigint
FROM logs
WHERE owner_id = $1
`

func (q *Queries) CountLogsForOwner(ctx context.Context, ownerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLogsForOwner, ownerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteFile = `-- name: DeleteFile :exec
UPDATE files
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const deleteFiles = `-- name: DeleteFiles :exec
WITH RECURSIVE t(id, parent_id) AS (
        SELECT id, parent_id
        FROM folders f
        WHERE f.id = $1
    UNION
        SELECT parent.id, parent.parent_id
        FROM folders parent, t cur
        WHERE parent.id = cur.parent_id
)
DELETE FROM files
WHERE parent_id IN (
    SELECT id FROM t
)
`

func (q *Queries) DeleteFiles(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFiles, id)
	return err
}

const deleteFolders = `-- name: DeleteFolders :exec
WITH RECURSIVE t(id, parent_id) AS (
        SELECT id, parent_id
        FROM folders f
        WHERE f.id = $1
    UNION
        SELECT parent.id, parent.parent_id
        FROM folders parent, t cur
        WHERE parent.id = cur.parent_id
)
DELETE FROM folders
WHERE id IN (
    SELECT id FROM t
)
`

func (q *Queries) DeleteFolders(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFolders, id)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :many
SELECT id, username, public_key FROM users
WHERE email ILIKE CONCAT('%', $1::TEXT, '%')
`

type FindUserByEmailRow struct {
	ID        int64  `json:"id"`
	Username  string `json:"username"`
	PublicKey []byte `json:"publicKey"`
}

func (q *Queries) FindUserByEmail(ctx context.Context, key string) ([]FindUserByEmailRow, error) {
	rows, err := q.db.Query(ctx, findUserByEmail, key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindUserByEmailRow{}
	for rows.Next() {
		var i FindUserByEmailRow
		if err := rows.Scan(&i.ID, &i.Username, &i.PublicKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUserByUsername = `-- name: FindUserByUsername :many
SELECT id, username, public_key FROM users
WHERE username ILIKE CONCAT('%', $1::TEXT, '%')
`

type FindUserByUsernameRow struct {
	ID        int64  `json:"id"`
	Username  string `json:"username"`
	PublicKey []byte `json:"publicKey"`
}

func (q *Queries) FindUserByUsername(ctx context.Context, key string) ([]FindUserByUsernameRow, error) {
	rows, err := q.db.Query(ctx, findUserByUsername, key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindUserByUsernameRow{}
	for rows.Next() {
		var i FindUserByUsernameRow
		if err := rows.Scan(&i.ID, &i.Username, &i.PublicKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveUploadSession = `-- name: GetActiveUploadSession :many
SELECT u.id, u.user_id, u.encrypted_metadata, u.parent_id, u.chunks, u.chunk_size, u.size, u.created_at, u.completed_at, u.expires_at, ARRAY_AGG(uc.chunk_index)::INT[] AS completed FROM uploads u
INNER JOIN upload_chunks uc ON u.id = uc.upload_id
WHERE user_id = $1 AND u.completed_at IS NULL AND u.expires_at > NOW()
GROUP BY u.id
`

type GetActiveUploadSessionRow struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"userId"`
	EncryptedMetadata []byte             `json:"encryptedMetadata"`
	ParentID          int64              `json:"parentId"`
	Chunks            int32              `json:"chunks"`
	ChunkSize         int64              `json:"chunkSize"`
	Size              int64              `json:"size"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	CompletedAt       pgtype.Timestamptz `json:"completedAt"`
	ExpiresAt         pgtype.Timestamptz `json:"expiresAt"`
	Completed         []int32            `json:"completed"`
}

func (q *Queries) GetActiveUploadSession(ctx context.Context, userID int64) ([]GetActiveUploadSessionRow, error) {
	rows, err := q.db.Query(ctx, getActiveUploadSession, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveUploadSessionRow{}
	for rows.Next() {
		var i GetActiveUploadSessionRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EncryptedMetadata,
			&i.ParentID,
			&i.Chunks,
			&i.ChunkSize,
			&i.Size,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.ExpiresAt,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChunk = `-- name: GetChunk :one
SELECT c.file_id, c.chunk_index, c.s3_key FROM file_chunks c
JOIN files f ON c.file_id = f.id
WHERE f.owner_id = $1 AND f.id = $3 AND c.chunk_index = $2
`

type GetChunkParams struct {
	OwnerID    int64 `json:"ownerId"`
	ChunkIndex int32 `json:"chunkIndex"`
	FileID     int64 `json:"fileId"`
}

func (q *Queries) GetChunk(ctx context.Context, arg GetChunkParams) (FileChunk, error) {
	row := q.db.QueryRow(ctx, getChunk, arg.OwnerID, arg.ChunkIndex, arg.FileID)
	var i FileChunk
	err := row.Scan(&i.FileID, &i.ChunkIndex, &i.S3Key)
	return i, err
}

const getChunks = `-- name: GetChunks :one
SELECT c.file_id, c.chunk_index, c.s3_key FROM file_chunks c
JOIN files f ON c.file_id = f.id
WHERE f.owner_id = $1 AND f.id = $2
`

type GetChunksParams struct {
	OwnerID int64 `json:"ownerId"`
	FileID  int64 `json:"fileId"`
}

func (q *Queries) GetChunks(ctx context.Context, arg GetChunksParams) (FileChunk, error) {
	row := q.db.QueryRow(ctx, getChunks, arg.OwnerID, arg.FileID)
	var i FileChunk
	err := row.Scan(&i.FileID, &i.ChunkIndex, &i.S3Key)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT id, owner_id, encrypted_metadata, encrypted_key, parent_id, chunks, chunk_size, size, created_at, deleted_at FROM files
WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.EncryptedMetadata,
		&i.EncryptedKey,
		&i.ParentID,
		&i.Chunks,
		&i.ChunkSize,
		&i.Size,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFiles = `-- name: GetFiles :many
SELECT id, owner_id, encrypted_metadata, encrypted_key, parent_id, chunks, chunk_size, size, created_at, deleted_at FROM files f
WHERE parent_id = $1 AND deleted_at ISNULL
`

func (q *Queries) GetFiles(ctx context.Context, parentID int64) ([]File, error) {
	rows, err := q.db.Query(ctx, getFiles, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.EncryptedMetadata,
			&i.EncryptedKey,
			&i.ParentID,
			&i.Chunks,
			&i.ChunkSize,
			&i.Size,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFolder = `-- name: GetFolder :one
SELECT id, encrypted_metadata, parent_id, owner_id, created_at, deleted_at FROM folders
WHERE id = $1 AND deleted_at ISNULL
`

func (q *Queries) GetFolder(ctx context.Context, id int64) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolder, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.EncryptedMetadata,
		&i.ParentID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFolderDepth = `-- name: GetFolderDepth :one
WITH RECURSIVE t(id, parent_id) AS (
        SELECT id, parent_id
        FROM folders f
        WHERE f.id = $1
    UNION
        SELECT parent.id, parent.parent_id
        FROM folders parent, t cur
        WHERE parent.id = cur.parent_id
)
SELECT COUNT(*) FROM t
`

func (q *Queries) GetFolderDepth(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getFolderDepth, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getKDFParameters = `-- name: GetKDFParameters :one
SELECT id, kdf_memory_cost, kdf_parallelism, kdf_salt, kdf_time_cost
FROM users
WHERE id = $1
`

type GetKDFParametersRow struct {
	ID             int64  `json:"id"`
	KdfMemoryCost  int32  `json:"kdfMemoryCost"`
	KdfParallelism int32  `json:"kdfParallelism"`
	KdfSalt        []byte `json:"kdfSalt"`
	KdfTimeCost    int32  `json:"kdfTimeCost"`
}

func (q *Queries) GetKDFParameters(ctx context.Context, id int64) (GetKDFParametersRow, error) {
	row := q.db.QueryRow(ctx, getKDFParameters, id)
	var i GetKDFParametersRow
	err := row.Scan(
		&i.ID,
		&i.KdfMemoryCost,
		&i.KdfParallelism,
		&i.KdfSalt,
		&i.KdfTimeCost,
	)
	return i, err
}

const getOpaqueClientRecord = `-- name: GetOpaqueClientRecord :one
SELECT id, username, opaque_record, credential_identifier FROM users
WHERE username = $1
`

type GetOpaqueClientRecordRow struct {
	ID                   int64  `json:"id"`
	Username             string `json:"username"`
	OpaqueRecord         []byte `json:"opaqueRecord"`
	CredentialIdentifier []byte `json:"credentialIdentifier"`
}

func (q *Queries) GetOpaqueClientRecord(ctx context.Context, username string) (GetOpaqueClientRecordRow, error) {
	row := q.db.QueryRow(ctx, getOpaqueClientRecord, username)
	var i GetOpaqueClientRecordRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.OpaqueRecord,
		&i.CredentialIdentifier,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, refresh_token, user_id, created_at, expires_at, last_used_at FROM sessions
WHERE refresh_token = $1
`

func (q *Queries) GetSession(ctx context.Context, refreshToken string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, refreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.RefreshToken,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getShare = `-- name: GetShare :one
SELECT s.id, s.file_id, s.sender_id, s.receiver_id, s.encrypted_fek, s.encrypted_metadata, s.created_at, s.expires_at, f.chunks, f.size, f.chunk_size FROM shares s
INNER JOIN files f ON s.file_id = f.id
WHERE s.id = $1 AND s.expires_at > NOW()
`

type GetShareRow struct {
	ID                int64              `json:"id"`
	FileID            int64              `json:"fileId"`
	SenderID          int64              `json:"senderId"`
	ReceiverID        int64              `json:"receiverId"`
	EncryptedFek      []byte             `json:"encryptedFek"`
	EncryptedMetadata []byte             `json:"encryptedMetadata"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt         pgtype.Timestamptz `json:"expiresAt"`
	Chunks            int32              `json:"chunks"`
	Size              int64              `json:"size"`
	ChunkSize         int64              `json:"chunkSize"`
}

func (q *Queries) GetShare(ctx context.Context, id int64) (GetShareRow, error) {
	row := q.db.QueryRow(ctx, getShare, id)
	var i GetShareRow
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.SenderID,
		&i.ReceiverID,
		&i.EncryptedFek,
		&i.EncryptedMetadata,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Chunks,
		&i.Size,
		&i.ChunkSize,
	)
	return i, err
}

const getShareChunk = `-- name: GetShareChunk :one
SELECT s.id, s.file_id, s.sender_id, s.receiver_id, s.encrypted_fek, s.encrypted_metadata, s.created_at, s.expires_at, c.file_id, c.chunk_index, c.s3_key FROM shares s
INNER JOIN files f ON s.file_id = f.id
INNER JOIN file_chunks c ON c.file_id = f.id
WHERE s.id = $1 AND c.chunk_index = $2 AND s.expires_at > NOW()
`

type GetShareChunkParams struct {
	ID         int64 `json:"id"`
	ChunkIndex int32 `json:"chunkIndex"`
}

type GetShareChunkRow struct {
	ID                int64              `json:"id"`
	FileID            int64              `json:"fileId"`
	SenderID          int64              `json:"senderId"`
	ReceiverID        int64              `json:"receiverId"`
	EncryptedFek      []byte             `json:"encryptedFek"`
	EncryptedMetadata []byte             `json:"encryptedMetadata"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt         pgtype.Timestamptz `json:"expiresAt"`
	FileID_2          int64              `json:"fileId2"`
	ChunkIndex        int32              `json:"chunkIndex"`
	S3Key             string             `json:"s3Key"`
}

func (q *Queries) GetShareChunk(ctx context.Context, arg GetShareChunkParams) (GetShareChunkRow, error) {
	row := q.db.QueryRow(ctx, getShareChunk, arg.ID, arg.ChunkIndex)
	var i GetShareChunkRow
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.SenderID,
		&i.ReceiverID,
		&i.EncryptedFek,
		&i.EncryptedMetadata,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.FileID_2,
		&i.ChunkIndex,
		&i.S3Key,
	)
	return i, err
}

const getShares = `-- name: GetShares :many
SELECT s.id, s.file_id, s.sender_id, s.receiver_id, s.encrypted_fek, s.encrypted_metadata, s.created_at, s.expires_at, u.username AS sender FROM shares s
INNER JOIN users u ON s.sender_id = u.id
WHERE s.receiver_id = $1 AND s.expires_at > NOW()
ORDER BY s.created_at DESC
LIMIT $2 OFFSET $3
`

type GetSharesParams struct {
	ReceiverID int64 `json:"receiverId"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

type GetSharesRow struct {
	ID                int64              `json:"id"`
	FileID            int64              `json:"fileId"`
	SenderID          int64              `json:"senderId"`
	ReceiverID        int64              `json:"receiverId"`
	EncryptedFek      []byte             `json:"encryptedFek"`
	EncryptedMetadata []byte             `json:"encryptedMetadata"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt         pgtype.Timestamptz `json:"expiresAt"`
	Sender            string             `json:"sender"`
}

func (q *Queries) GetShares(ctx context.Context, arg GetSharesParams) ([]GetSharesRow, error) {
	rows, err := q.db.Query(ctx, getShares, arg.ReceiverID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSharesRow{}
	for rows.Next() {
		var i GetSharesRow
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.SenderID,
			&i.ReceiverID,
			&i.EncryptedFek,
			&i.EncryptedMetadata,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Sender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharesBySender = `-- name: GetSharesBySender :many
SELECT
    s.id, s.sender_id, s.receiver_id, u.username AS receiver,
    f.encrypted_metadata, s.created_at, s.expires_at
FROM shares s
INNER JOIN files f ON s.file_id = f.id
INNER JOIN users u ON s.receiver_id = u.id
WHERE s.sender_id = $1 AND s.expires_at > NOW()
ORDER BY s.created_at DESC
LIMIT $2 OFFSET $3
`

type GetSharesBySenderParams struct {
	SenderID int64 `json:"senderId"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type GetSharesBySenderRow struct {
	ID                int64              `json:"id"`
	SenderID          int64              `json:"senderId"`
	ReceiverID        int64              `json:"receiverId"`
	Receiver          string             `json:"receiver"`
	EncryptedMetadata []byte             `json:"encryptedMetadata"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt         pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) GetSharesBySender(ctx context.Context, arg GetSharesBySenderParams) ([]GetSharesBySenderRow, error) {
	rows, err := q.db.Query(ctx, getSharesBySender, arg.SenderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSharesBySenderRow{}
	for rows.Next() {
		var i GetSharesBySenderRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Receiver,
			&i.EncryptedMetadata,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubfolders = `-- name: GetSubfolders :many
SELECT id, encrypted_metadata, parent_id, owner_id, created_at, deleted_at FROM folders
WHERE parent_id = $1 AND deleted_at ISNULL
`

func (q *Queries) GetSubfolders(ctx context.Context, parentID pgtype.Int8) ([]Folder, error) {
	rows, err := q.db.Query(ctx, getSubfolders, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.EncryptedMetadata,
			&i.ParentID,
			&i.OwnerID,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUploadChunk = `-- name: GetUploadChunk :one
SELECT upload_id, chunk_index, s3_key, completed FROM upload_chunks
WHERE upload_id = $1 AND chunk_index = $2
`

type GetUploadChunkParams struct {
	UploadID   int64 `json:"uploadId"`
	ChunkIndex int32 `json:"chunkIndex"`
}

func (q *Queries) GetUploadChunk(ctx context.Context, arg GetUploadChunkParams) (UploadChunk, error) {
	row := q.db.QueryRow(ctx, getUploadChunk, arg.UploadID, arg.ChunkIndex)
	var i UploadChunk
	err := row.Scan(
		&i.UploadID,
		&i.ChunkIndex,
		&i.S3Key,
		&i.Completed,
	)
	return i, err
}

const getUploadSession = `-- name: GetUploadSession :one
SELECT id, user_id, encrypted_metadata, parent_id, chunks, chunk_size, size, created_at, completed_at, expires_at FROM uploads
WHERE id = $1 AND completed_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetUploadSession(ctx context.Context, id int64) (Upload, error) {
	row := q.db.QueryRow(ctx, getUploadSession, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedMetadata,
		&i.ParentID,
		&i.Chunks,
		&i.ChunkSize,
		&i.Size,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUsedCapacity = `-- name: GetUsedCapacity :one
SELECT COALESCE(SUM(size), 0)::BIGINT FROM files
WHERE owner_id = $1 AND deleted_at ISNULL
`

func (q *Queries) GetUsedCapacity(ctx context.Context, ownerID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getUsedCapacity, ownerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, username, opaque_record, credential_identifier, permission, capacity, kdf_salt, kdf_memory_cost, kdf_time_cost, kdf_parallelism, public_key, encrypted_private_key, root_folder, is_active, is_locked, created_at, updated_at, last_login_at FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.OpaqueRecord,
		&i.CredentialIdentifier,
		&i.Permission,
		&i.Capacity,
		&i.KdfSalt,
		&i.KdfMemoryCost,
		&i.KdfTimeCost,
		&i.KdfParallelism,
		&i.PublicKey,
		&i.EncryptedPrivateKey,
		&i.RootFolder,
		&i.IsActive,
		&i.IsLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one

SELECT id, email, username, opaque_record, credential_identifier, permission, capacity, kdf_salt, kdf_memory_cost, kdf_time_cost, kdf_parallelism, public_key, encrypted_private_key, root_folder, is_active, is_locked, created_at, updated_at, last_login_at FROM users
WHERE username = $1
`

// #region Sharing
func (q *Queries) GetUserByName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.OpaqueRecord,
		&i.CredentialIdentifier,
		&i.Permission,
		&i.Capacity,
		&i.KdfSalt,
		&i.KdfMemoryCost,
		&i.KdfTimeCost,
		&i.KdfParallelism,
		&i.PublicKey,
		&i.EncryptedPrivateKey,
		&i.RootFolder,
		&i.IsActive,
		&i.IsLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const insertLog = `-- name: InsertLog :exec
INSERT INTO logs (owner_id, level, message, encrypted_metadata)
VALUES ($1, $2, $3, $4)
`

type InsertLogParams struct {
	OwnerID           int64    `json:"ownerId"`
	Level             LogLevel `json:"level"`
	Message           []byte   `json:"message"`
	EncryptedMetadata []byte   `json:"encryptedMetadata"`
}

func (q *Queries) InsertLog(ctx context.Context, arg InsertLogParams) error {
	_, err := q.db.Exec(ctx, insertLog,
		arg.OwnerID,
		arg.Level,
		arg.Message,
		arg.EncryptedMetadata,
	)
	return err
}

const invalidateShare = `-- name: InvalidateShare :exec
UPDATE shares
SET expires_at = NOW()
WHERE id = $1
`

func (q *Queries) InvalidateShare(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, invalidateShare, id)
	return err
}

const listLogsForOwner = `-- name: ListLogsForOwner :many
SELECT id, level, message, encrypted_metadata, created_at
FROM logs
WHERE owner_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListLogsForOwnerParams struct {
	OwnerID int64 `json:"ownerId"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type ListLogsForOwnerRow struct {
	ID                int64              `json:"id"`
	Level             LogLevel           `json:"level"`
	Message           []byte             `json:"message"`
	EncryptedMetadata []byte             `json:"encryptedMetadata"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
}

func (q *Queries) ListLogsForOwner(ctx context.Context, arg ListLogsForOwnerParams) ([]ListLogsForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listLogsForOwner, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLogsForOwnerRow{}
	for rows.Next() {
		var i ListLogsForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Level,
			&i.Message,
			&i.EncryptedMetadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const migrateChunks = `-- name: MigrateChunks :exec
INSERT INTO
    file_chunks (file_id, chunk_index, s3_key)
SELECT 
    $1 AS file_id, chunk_index, s3_key
FROM upload_chunks
WHERE upload_id = $2 AND completed = TRUE
`

type MigrateChunksParams struct {
	FileID   int64 `json:"fileId"`
	UploadID int64 `json:"uploadId"`
}

func (q *Queries) MigrateChunks(ctx context.Context, arg MigrateChunksParams) error {
	_, err := q.db.Exec(ctx, migrateChunks, arg.FileID, arg.UploadID)
	return err
}

const migrateUpload = `-- name: MigrateUpload :one
INSERT INTO
    files (owner_id, encrypted_metadata, parent_id, encrypted_key, chunks, size, chunk_size)
SELECT
    user_id, encrypted_metadata, parent_id, $2 AS encrypted_key, chunks, size, chunk_size
FROM uploads u
WHERE u.id = $1
RETURNING id
`

type MigrateUploadParams struct {
	ID           int64  `json:"id"`
	EncryptedKey []byte `json:"encryptedKey"`
}

func (q *Queries) MigrateUpload(ctx context.Context, arg MigrateUploadParams) (int64, error) {
	row := q.db.QueryRow(ctx, migrateUpload, arg.ID, arg.EncryptedKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const newFile = `-- name: NewFile :one
INSERT INTO files (
    owner_id, encrypted_metadata, encrypted_key,
    chunks, size
)
VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, owner_id, encrypted_metadata, encrypted_key, parent_id, chunks, chunk_size, size, created_at, deleted_at
`

type NewFileParams struct {
	OwnerID           int64  `json:"ownerId"`
	EncryptedMetadata []byte `json:"encryptedMetadata"`
	EncryptedKey      []byte `json:"encryptedKey"`
	Chunks            int32  `json:"chunks"`
	Size              int64  `json:"size"`
}

func (q *Queries) NewFile(ctx context.Context, arg NewFileParams) (File, error) {
	row := q.db.QueryRow(ctx, newFile,
		arg.OwnerID,
		arg.EncryptedMetadata,
		arg.EncryptedKey,
		arg.Chunks,
		arg.Size,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.EncryptedMetadata,
		&i.EncryptedKey,
		&i.ParentID,
		&i.Chunks,
		&i.ChunkSize,
		&i.Size,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const newFolder = `-- name: NewFolder :one
INSERT INTO folders(encrypted_metadata, parent_id, owner_id)
VALUES ($1, $2, $3)
RETURNING id, encrypted_metadata, parent_id, owner_id, created_at, deleted_at
`

type NewFolderParams struct {
	EncryptedMetadata []byte      `json:"encryptedMetadata"`
	ParentID          pgtype.Int8 `json:"parentId"`
	OwnerID           int64       `json:"ownerId"`
}

func (q *Queries) NewFolder(ctx context.Context, arg NewFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, newFolder, arg.EncryptedMetadata, arg.ParentID, arg.OwnerID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.EncryptedMetadata,
		&i.ParentID,
		&i.OwnerID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const newSession = `-- name: NewSession :one
INSERT INTO sessions (refresh_token, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING id, refresh_token, user_id, created_at, expires_at, last_used_at
`

type NewSessionParams struct {
	RefreshToken string             `json:"refreshToken"`
	UserID       int64              `json:"userId"`
	ExpiresAt    pgtype.Timestamptz `json:"expiresAt"`
}

func (q *Queries) NewSession(ctx context.Context, arg NewSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, newSession, arg.RefreshToken, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.RefreshToken,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const newShare = `-- name: NewShare :one
INSERT INTO shares(file_id, sender_id, receiver_id, encrypted_fek, encrypted_metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, file_id, sender_id, receiver_id, encrypted_fek, encrypted_metadata, created_at, expires_at
`

type NewShareParams struct {
	FileID            int64  `json:"fileId"`
	SenderID          int64  `json:"senderId"`
	ReceiverID        int64  `json:"receiverId"`
	EncryptedFek      []byte `json:"encryptedFek"`
	EncryptedMetadata []byte `json:"encryptedMetadata"`
}

func (q *Queries) NewShare(ctx context.Context, arg NewShareParams) (Share, error) {
	row := q.db.QueryRow(ctx, newShare,
		arg.FileID,
		arg.SenderID,
		arg.ReceiverID,
		arg.EncryptedFek,
		arg.EncryptedMetadata,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.SenderID,
		&i.ReceiverID,
		&i.EncryptedFek,
		&i.EncryptedMetadata,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const newUpload = `-- name: NewUpload :one
INSERT INTO uploads (
    user_id, chunks, chunk_size, size, expires_at, parent_id, encrypted_metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, encrypted_metadata, parent_id, chunks, chunk_size, size, created_at, completed_at, expires_at
`

type NewUploadParams struct {
	UserID            int64              `json:"userId"`
	Chunks            int32              `json:"chunks"`
	ChunkSize         int64              `json:"chunkSize"`
	Size              int64              `json:"size"`
	ExpiresAt         pgtype.Timestamptz `json:"expiresAt"`
	ParentID          int64              `json:"parentId"`
	EncryptedMetadata []byte             `json:"encryptedMetadata"`
}

func (q *Queries) NewUpload(ctx context.Context, arg NewUploadParams) (Upload, error) {
	row := q.db.QueryRow(ctx, newUpload,
		arg.UserID,
		arg.Chunks,
		arg.ChunkSize,
		arg.Size,
		arg.ExpiresAt,
		arg.ParentID,
		arg.EncryptedMetadata,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EncryptedMetadata,
		&i.ParentID,
		&i.Chunks,
		&i.ChunkSize,
		&i.Size,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const newUploadChunk = `-- name: NewUploadChunk :exec
INSERT INTO upload_chunks (upload_id, chunk_index, s3_key, completed)
VALUES ($1, $2, $3, false)
`

type NewUploadChunkParams struct {
	UploadID   int64  `json:"uploadId"`
	ChunkIndex int32  `json:"chunkIndex"`
	S3Key      string `json:"s3Key"`
}

func (q *Queries) NewUploadChunk(ctx context.Context, arg NewUploadChunkParams) error {
	_, err := q.db.Exec(ctx, newUploadChunk, arg.UploadID, arg.ChunkIndex, arg.S3Key)
	return err
}

const newUser = `-- name: NewUser :one
INSERT INTO users (
    email, username, opaque_record, credential_identifier, permission, capacity,
    kdf_salt, kdf_memory_cost, kdf_time_cost, kdf_parallelism,
    public_key, encrypted_private_key, root_folder
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, email, username, opaque_record, credential_identifier, permission, capacity, kdf_salt, kdf_memory_cost, kdf_time_cost, kdf_parallelism, public_key, encrypted_private_key, root_folder, is_active, is_locked, created_at, updated_at, last_login_at
`

type NewUserParams struct {
	Email                string      `json:"email"`
	Username             string      `json:"username"`
	OpaqueRecord         []byte      `json:"opaqueRecord"`
	CredentialIdentifier []byte      `json:"credentialIdentifier"`
	Permission           int64       `json:"permission"`
	Capacity             int64       `json:"capacity"`
	KdfSalt              []byte      `json:"kdfSalt"`
	KdfMemoryCost        int32       `json:"kdfMemoryCost"`
	KdfTimeCost          int32       `json:"kdfTimeCost"`
	KdfParallelism       int32       `json:"kdfParallelism"`
	PublicKey            []byte      `json:"publicKey"`
	EncryptedPrivateKey  []byte      `json:"encryptedPrivateKey"`
	RootFolder           pgtype.Int8 `json:"rootFolder"`
}

func (q *Queries) NewUser(ctx context.Context, arg NewUserParams) (User, error) {
	row := q.db.QueryRow(ctx, newUser,
		arg.Email,
		arg.Username,
		arg.OpaqueRecord,
		arg.CredentialIdentifier,
		arg.Permission,
		arg.Capacity,
		arg.KdfSalt,
		arg.KdfMemoryCost,
		arg.KdfTimeCost,
		arg.KdfParallelism,
		arg.PublicKey,
		arg.EncryptedPrivateKey,
		arg.RootFolder,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.OpaqueRecord,
		&i.CredentialIdentifier,
		&i.Permission,
		&i.Capacity,
		&i.KdfSalt,
		&i.KdfMemoryCost,
		&i.KdfTimeCost,
		&i.KdfParallelism,
		&i.PublicKey,
		&i.EncryptedPrivateKey,
		&i.RootFolder,
		&i.IsActive,
		&i.IsLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const rotateSession = `-- name: RotateSession :exec
UPDATE sessions
SET refresh_token = $2, last_used_at = NOW()
WHERE refresh_token = $1
`

type RotateSessionParams struct {
	RefreshToken string `json:"refreshToken"`
	NewToken     string `json:"newToken"`
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) error {
	_, err := q.db.Exec(ctx, rotateSession, arg.RefreshToken, arg.NewToken)
	return err
}

const setFileMetadata = `-- name: SetFileMetadata :exec
UPDATE files
SET encrypted_metadata = $1
WHERE id = $2
`

type SetFileMetadataParams struct {
	EncryptedMetadata []byte `json:"encryptedMetadata"`
	ID                int64  `json:"id"`
}

func (q *Queries) SetFileMetadata(ctx context.Context, arg SetFileMetadataParams) error {
	_, err := q.db.Exec(ctx, setFileMetadata, arg.EncryptedMetadata, arg.ID)
	return err
}

const setFileParent = `-- name: SetFileParent :exec
UPDATE files
SET parent_id = $2
WHERE id = $1
`

type SetFileParentParams struct {
	ID       int64 `json:"id"`
	ParentID int64 `json:"parentId"`
}

func (q *Queries) SetFileParent(ctx context.Context, arg SetFileParentParams) error {
	_, err := q.db.Exec(ctx, setFileParent, arg.ID, arg.ParentID)
	return err
}

const setFolderMetadata = `-- name: SetFolderMetadata :exec
UPDATE folders
SET encrypted_metadata = $1
WHERE id = $2
`

type SetFolderMetadataParams struct {
	EncryptedMetadata []byte `json:"encryptedMetadata"`
	ID                int64  `json:"id"`
}

func (q *Queries) SetFolderMetadata(ctx context.Context, arg SetFolderMetadataParams) error {
	_, err := q.db.Exec(ctx, setFolderMetadata, arg.EncryptedMetadata, arg.ID)
	return err
}

const setRootFolder = `-- name: SetRootFolder :exec
UPDATE users
SET root_folder = $1
WHERE id = $2
`

type SetRootFolderParams struct {
	RootFolder pgtype.Int8 `json:"rootFolder"`
	ID         int64       `json:"id"`
}

func (q *Queries) SetRootFolder(ctx context.Context, arg SetRootFolderParams) error {
	_, err := q.db.Exec(ctx, setRootFolder, arg.RootFolder, arg.ID)
	return err
}

const traverseFiles = `-- name: TraverseFiles :many
WITH RECURSIVE t(id, parent_id) AS (
        SELECT id, parent_id
        FROM folders f
        WHERE f.id = $1
    UNION
        SELECT parent.id, parent.parent_id
        FROM folders parent, t cur
        WHERE parent.id = cur.parent_id
)
SELECT id, owner_id, encrypted_metadata, encrypted_key, parent_id, chunks, chunk_size, size, created_at, deleted_at
FROM files
WHERE id IN (
    SELECT id FROM t
)
`

func (q *Queries) TraverseFiles(ctx context.Context, id int64) ([]File, error) {
	rows, err := q.db.Query(ctx, traverseFiles, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.EncryptedMetadata,
			&i.EncryptedKey,
			&i.ParentID,
			&i.Chunks,
			&i.ChunkSize,
			&i.Size,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const traverseTree = `-- name: TraverseTree :many
WITH RECURSIVE t(id, parent_id) AS (
        SELECT id, parent_id
        FROM folders f
        WHERE f.id = $1
    UNION
        SELECT parent.id, parent.parent_id
        FROM folders parent, t cur
        WHERE parent.id = cur.parent_id
)
SELECT id FROM t
`

func (q *Queries) TraverseTree(ctx context.Context, id int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, traverseTree, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
